// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cramer_statistic_cols
double cramer_statistic_cols(NumericMatrix xt, NumericMatrix yt, int kernel, int chunk);
RcppExport SEXP _fastcramer_cramer_statistic_cols(SEXP xtSEXP, SEXP ytSEXP, SEXP kernelSEXP, SEXP chunkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xt(xtSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type yt(ytSEXP);
    Rcpp::traits::input_parameter< int >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< int >::type chunk(chunkSEXP);
    rcpp_result_gen = Rcpp::wrap(cramer_statistic_cols(xt, yt, kernel, chunk));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastcramer_cramer_statistic_cols", (DL_FUNC) &_fastcramer_cramer_statistic_cols, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastcramer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
