# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname cramer_statistic
#' @param xt,yt Numeric matrices with observations in COLUMNS (d x m and d x n).
#' @param kernel Integer kernel code: 0 cramer, 1 bahr, 2 log, 3 fraca, 4 fracb.
#' @param chunk Rows of the cross-product block held in memory at once.
#' @keywords internal
cramer_statistic_cols <- function(xt, yt, kernel = 0L, chunk = 2000L) {
    .Call(`_fastcramer_cramer_statistic_cols`, xt, yt, kernel, chunk)
}

